### ISSUE TITLE
add 2019 map page

### ISSUE THREAD

**Issue by lufthans** [SeaGL/seagl.github.io#131]
* the map link points to a page that doesn't exist
** https://seagl.org/maps/2019.html
** can we add a screen capture image from OSM on this year's page in addition to the link to Google maps?
** it would also be nice to point out cross streets and name the nearby railstop
** maybe mention it's across from the Jimi Hendrix statue as that's easy
to remember and likely to be recognized

related: https://github.com/SeaGL/seagl.github.io/issues/96

**Comment by altsalt** [comment]
Btw, I did address this issue with commit 2ca391139c5e434a86ae0befde6edca85d12b212 but it doesn't address migrating to OSM so I won't close the issue outright.

**Comment by meonkeys** [comment]
We have a map page for 2019, but see also #145 , #146
