### ISSUE TITLE
Clarify parking instructions

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/seagl.github.io#171]
Our [existing](https://seagl.org/maps/2019.html) parking instructions are confusing:

  - We direct attendees to the Harvard Garage, but then tell them not to use it.

    > …make an immediate left turn into the Harvard Ave. parking garage.

    > …go one block west to the Parking Garage located at Harvard and Pine.

    > Please use street parking or private parking. SCC's lots are for teachers and students.

  - We suggest that there are parking lots near the front entrance to SCC, but actually that's at a local maximum distance from parking lots:

    > There are several private parking lots located near the front entrance at 1701 Broadway Ave. or on Harvard Avenue

    <img src="https://user-images.githubusercontent.com/1844746/76649979-ea25ee00-651e-11ea-8454-eadcebdbc814.png" alt="map" width="360">

**Comment by koronkowy** [comment]
I suggest closing this issue as we are 2 years ahead in time and due to the pandemic not operating physically this year.
