### ISSUE TITLE
404 for http://seagl.org/schedule/2015.html

### ISSUE THREAD

**Issue by meonkeys** [SeaGL/seagl.github.io#23]
Maybe just put up a stub/"coming soon" page for now?

This "failgull" page was recommended by `penglish2`:

![](http://www.felipepita.com.br/wp-content/uploads/2009/12/seagull_fail.jpg)

Could use that for 404 or 500 errors.

**Comment by ex-nerd** [comment]
Copyright on the image is...?

**Comment by meonkeys** [comment]
No idea.

**Comment by edunham** [comment]
Fixed in https://github.com/SeaGL/seagl.github.io/commit/23f54f00b517a08a14f900f51378bb1b980f0f31
