### ISSUE TITLE
/schedule is out of date

### ISSUE THREAD

**Issue by nhandler** [SeaGL/seagl.github.io#281]
https://seagl.org/schedule/ currently shows SeaGL 2013 and 2014. It is rather out-of-date. It should either be updated, merged with some of the archive work that is taking place, or removed.

**Comment by altsalt** [comment]
Thanks @nhandler ! @AndrewKvalheim making sure you have eyes on this.

**Comment by AndrewKvalheim** [comment]
Thanks, how did you find that? Is it linked from somewhere?
