### ISSUE TITLE
Update CoC

### ISSUE THREAD

**Issue by koronkowy** [SeaGL/seagl.github.io#283]
The CoC is ready to be updated on the site but it lives in markdown form.

See: https://github.com/SeaGL/organization/blob/main/Code-of-Conduct.md

If this can happen ASAP that would be great.

**Comment by altsalt** [comment]
We'll go over this as an item at the SeaGL/organization#187

**Comment by AndrewKvalheim** [comment]
I’ve converted most content pages to markdown now so it should be easy to swap this in after the meeting.
