### ISSUE TITLE
Add the 2015 sponsor prospectus

### ISSUE THREAD

**Issue by edunham** [SeaGL/seagl.github.io#29]

**Comment by edunham** [comment]
@eximious, are you right person to ask whether the one in Google Drive is sufficiently final to be published?

**Comment by eximious** [comment]
Hi,
I actually just pinged Rob about this.  It is ready to publish, but I'm not
sure how to attach it to the link.
Deb

**Comment by edunham** [comment]
@eximious ok, thanks for confirming. If nobody else has done it by this afternoon, I'll pdf what's in the drive and add it to the site.

**Comment by eximious** [comment]
Thanks Emily!

**Comment by edunham** [comment]
added it and the sponsor form in the PR. I haven't linked the sponsorship agreement from anywhere, but having the pdf in the repo makes it more discoverable.
