### ISSUE TITLE
2015 Maps Page Needs Added

### ISSUE THREAD

**Issue by chasemaier** [SeaGL/seagl.github.io#34]
Looks like a 2015 maps page needs created. Current link goes to http://seagl.org/maps/2015.html.
* https://github.com/SeaGL/seagl.github.io/blob/master/index.html#L24
* https://github.com/SeaGL/seagl.github.io/blob/master/_config.yml#L17
* https://github.com/SeaGL/seagl.github.io/tree/master/maps (no 2015.html, no 2013.html)

Also some invalid older links:
* https://github.com/SeaGL/seagl.github.io/blob/master/maps/index.html#L11

**Comment by altsalt** [comment]
Fixed in 2ca66103f81644f5f9448bc769314677a9430086
