### ISSUE TITLE
Review /attend/existing

### ISSUE THREAD

**Issue by strugee** [SeaGL/seagl.github.io#359]

**Comment by frenata** [comment]
![Screenshot_20221027-164215](https://user-images.githubusercontent.com/10249330/198394064-3700c27b-bc9e-475b-970f-d7e6ab41bcf8.jpg)

First blocker. ;)

**Comment by strugee** [comment]
This blocker is _technically_ fixed by #363 (it redirects to a fictional "Pure Functions Conference" space that we use for testing [the bot](https://github.com/SeaGL/patch) that creates all the rooms). YMMV though because half the screenshots are missing still - I'm blocked on taking them for various reasons
