### ISSUE TITLE
participant registration link is hard to find

### ISSUE THREAD

**Issue by edunham** [SeaGL/seagl.github.io#37]
we need a link on the 'get involved' page, presumably pointing at osem.seagl.org

**Comment by tedmcox** [comment]
We should probably remove the graf on the Cascadia Builder Award, too, as the selection process has closed.

**Comment by altsalt** [comment]
Partially fixed with 7028920b8d896e9a74850f14cd93380dac41cde2

Get Involved page still needs updating.
