### ISSUE TITLE
Add Linkedin link

### ISSUE THREAD

**Issue by mateuskrause** [SeaGL/seagl.github.io#398]
We have a linkedin profile [(https://www.linkedin.com/company/seagl/)](https://www.linkedin.com/company/seagl/)
It would be good to have a link in the footer.

(discussed at outreach meeting, jun-08)

**Comment by altsalt** [comment]
Added in https://github.com/SeaGL/seagl.github.io/commit/ed670797566aff13a1910e601b5f00d6db9f1edd
