### ISSUE TITLE
2016 Schedule and Sponsors pages throw a 404 error

### ISSUE THREAD

**Issue by tedmcox** [SeaGL/seagl.github.io#63]
http://seagl.org/schedule/2016.html

http://seagl.org/sponsors/2016.html

Maybe we can add a "coming soon" section.

**Comment by shanet** [comment]
Sponsors page is addressed in #67.

**Comment by shanet** [comment]
Stub pages added in c02314f5c1299ea91195faa4d18067ae9a909c16 and 58456594b5853c0c08a996e014b70f209cf48798.
