### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by ghost** [SeaGL/seagl.github.io#85]
Hi there, I've been approached by Salt to give feedback on style related topics. Here are some things that come to my mind that could be relevant for people working on SeaGL material. It is a mix of food for thought but also ideas on how to maybe change existing things.

# Fonts
* So you use Dosis and Lato. Stick to those, you should be able to cover any circumstance with them, especially with Latos [variety of cuts](https://fonts.google.com/specimen/Lato). Keeping an eye on not using different fonts is essential for recognition.  
* I'd try to settle on one set of size ratios between Dosis and Lato. make sure Dosis is never smaller but always bigger than Lato like here:
![image](https://cloud.githubusercontent.com/assets/164785/26561768/33d431be-44c1-11e7-9942-0e9447149bdc.png)
*(Lato is used quite small here)*
* Stick to Dosis on capitals ONLY. Mixing non-capital with Lato probably does not work well.
* Don't use Dosis smaller than the current top menu: 
![image](https://cloud.githubusercontent.com/assets/164785/26561982/ee27d704-44c2-11e7-8279-3ba89ca0f53e.png)

# Borders
Find a common set of borders that are allowed. **This** should ideally not be possible by such a given set:
![image](https://cloud.githubusercontent.com/assets/164785/26562031/31389650-44c3-11e7-9cad-619fa064043d.png)
choose a set of attributes that work for you and stick to only those:
* borderless/bordered
* thin/thick borders
* opaque/transparent borders
* bright/dark borders
And of course try to be consistent and not use different degrees of any attribute.

# 45° Edgyness
Edges are part of your look (like in the Seagull and the banner border). Come back to this property when creating any new elements or designs. Try finding subtle opportunities to include a 45° angle everywhere. 

# Colors
* Narrow down your palette to a small number of colors that are not too close to each other and try sticking to those. Use shades only if necessary. Start by only looking at colors in your logo and see how far you can go by limiting your colors exclusively to those. Example: there should not be three different blues here: 
![image](https://cloud.githubusercontent.com/assets/164785/26562504/03f66150-44c7-11e7-821a-ad83ddfc7a54.png)
or here:
![image](https://cloud.githubusercontent.com/assets/164785/26562528/2458a890-44c7-11e7-849b-841a4083290e.png)

* Make this your new default white for all backgrounds:
![image](https://cloud.githubusercontent.com/assets/164785/26562366/082b66ae-44c6-11e7-9145-d17a72675745.png)

* avoid combinations with bad readability by either defining specific arrangements that work good enough - or - make it a rule not to use them.*("text on orange background has to be dark blue")*
![image](https://cloud.githubusercontent.com/assets/164785/26562429/7224e026-44c6-11e7-8610-74e6b4740644.png)

# Gradients
Embrace them or avoid them if possible:
![image](https://cloud.githubusercontent.com/assets/164785/26562647/6eca4f2c-44c8-11e7-95f2-0834dcdd99ca.png)

**Comment by altsalt** [comment]
tyvm!

**Comment by meonkeys** [comment]
This is awesome. We should put this in a wiki page / Markdown file for permanent reference.

**Comment by AndrewKvalheim** [comment]
> <del>**Style**</del> **Style guide**

Seems more like *advice for creating* a style guide to me, not an actual guide yet.

**Comment by altsalt** [comment]
Completed in #289
