### ISSUE TITLE
More deps need installing for local dev - bare metal

### ISSUE THREAD

**Issue by vmbrasseur** [SeaGL/seagl.github.io#87]
At least on macOS, after installing the jekyll gem I also had to install the following to get jekyll to work:

* bundler
* github-pages

The docs should probably be updated. I'll try to do that in a bit.

**Comment by AndrewKvalheim** [comment]
This can be closed; `bundle install` is [now][diff] documented.

[diff]: https://github.com/SeaGL/seagl.github.io/commit/c8163c0c9590b0b8c3e27818a1b5794f9c1b4c39?diff=split#diff-04c6e90faac2675aa89e2176d2eec7d8R108
